trigger:
- main

pool:
  name: Default   # aqu√≠ va el nombre de tu pool de agentes

steps:
- script: |
    echo "Usando el agente local de Alexis"
    whoami
    echo "Proyecto ejecutado"
  displayName: 'Ejecutar en agente local'
